import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0D1321",
    padding: 16,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginBottom: 20,
    marginTop: 20,
  },
  nextScheduleText: {
    fontSize: 26,
    fontWeight: "bold",
    textAlign: "center",
    color: "#F0EBD8",
    marginVertical: 20,
  },
  nextScheduleBox: {
    borderRadius: 16,
    marginVertical: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#3E5C76",
  },
  addButton: {
    backgroundColor: "#3E5C76",
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  addButtonText: {
    color: "#F0EBD8",
    fontSize: 28,
    fontWeight: "bold",
  },
  deleteButton: {
    backgroundColor: "#3E5C76",
    padding: 8,
    borderRadius: 20,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#3E5C76",
    marginLeft: 'auto',
  },
  deleteButtonText: {
    color: "#F0EBD8",
    fontSize: 16,
    fontWeight: "bold",
    lineHeight: 20,
  },
  eventList: {
    flexGrow: 1,
  },
  eventBox: {
    backgroundColor: "#1D2D44",
    padding: 20,
    borderRadius: 16,
    marginVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#3E5C76",
  },
  eventTime: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#F0EBD8",
    flex: 3,
    marginRight: 12,
  },
  eventDetail: {
    fontSize: 14,
    color: "#748CAB",
    flex: 2,
    fontWeight: "500",
    marginRight: 8,
  },
  eventTemperature: {
    fontSize: 18,
    color: "#F0EBD8",
    fontWeight: "600",
    flex: 2,
    textAlign: "center",
    marginRight: 12,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0D1321",
  },
  modalContent: {
    width: "90%",
    backgroundColor: "#1D2D44",
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: "#748CAB",
  },
  modalTitle: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#F0EBD8",
    textAlign: "center",
  },
  inputContainer: {
    marginBottom: 15,
  },
  inputLabel: {
    fontSize: 16,
    color: "#748CAB",
    marginBottom: 8,
    fontWeight: "500",
  },
  input: {
    borderWidth: 1.5,
    borderColor: "#3E5C76",
    padding: 14,
    borderRadius: 12,
    fontSize: 16,
    backgroundColor: "#0D1321",
    color: "#F0EBD8",
  },
  timeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  timeInput: {
    flex: 1,
    marginHorizontal: 4,
  },
  amPmButton: {
    backgroundColor: "#3E5C76",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    minWidth: 80,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#748CAB",
  },
  amPmButtonText: {
    color: "#F0EBD8",
    fontSize: 16,
    fontWeight: "600",
  },
  toggleContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#0D1321",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#3E5C76",
  },
  toggleLabel: {
    fontSize: 16,
    color: "#748CAB",
    fontWeight: "500",
  },
  actionButton: {
    backgroundColor: "#3E5C76",
    padding: 16,
    borderRadius: 12,
    marginTop: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#748CAB",
  },
  cancelButton: {
    backgroundColor: "#1D2D44",
    padding: 16,
    borderRadius: 12,
    marginTop: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#748CAB",
  },
  actionButtonText: {
    color: "#F0EBD8",
    fontSize: 16,
    fontWeight: "600",
  },
  cancelButtonText: {
    color: "#F0EBD8",
    fontSize: 16,
    fontWeight: "600",
  },
  defaultEventBox: {
    borderWidth: 2,
    borderColor: "#3E5C76",
    backgroundColor: "#1D2D44",
  },
  gradientBackground: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
});

export default styles;
