import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0D1321',
    padding: 20,
  },
  statusText: {
    color: '#F0EBD8',
    fontSize: 14,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    borderWidth: 1,
    borderColor: "#3E5C76",
    borderRadius: 15,
    paddingVertical: 10,
    paddingHorizontal: 20,
    textAlign: 'center',
    marginVertical: 15, 
  },
  temperatureContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 20,
  },
  temperatureBarContainer: {
    width: '100%',
    height: 20,
    marginBottom: 20,
    position: 'relative',
  },
  temperatureBar: {
    height: 20,
    borderRadius: 10,
    width: '100%',
    backgroundColor: '#3E5C76',
  },
  marker: {
    position: 'absolute',
    top: -15,
    transform: [{ translateX: -10 }],
    zIndex: 1,
  },
  triangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderTopWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#F0EBD8', 
  },
  controlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 20,
  },
  controlButton: {
    width: 60,
    height: 60,
    backgroundColor: '#3E5C76',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  buttonText: {
    fontSize: 30,
    color: '#F0EBD8',
  },
  valueText: {
    fontSize: 48,
    color: '#F0EBD8',
    fontWeight: 'bold',
  },
  modeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  modeButton: {
    width: 100,
    height: 100,
    backgroundColor: '#1D2D44',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedMode: {
    backgroundColor: '#F0EBD8',
  },
  modeIcon: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  selectedText: {
    color: '#000',
  },
  gradientBackground: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
});
