import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E6F3FF',
    padding: 16,
  },
  nextScheduleContainer: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#CDDDE2',
  },
  nextScheduleText: {
    fontSize: 16,
    textAlign: 'center',
    color: '#2196F3',
    fontWeight: '600',
  },
  calendar: {
    borderRadius: 10,
    elevation: 4,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#CDDDE2',
  },
  addBar: {
    backgroundColor: '#23C4FF',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#CDDDE2',
  },
  addBarText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  schedulesList: {
    flex: 1,
  },
  scheduleItem: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#CDDDE2',
  },
  scheduleInfo: {
    flex: 1,
  },
  scheduleTime: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  scheduleDate: {
    fontSize: 14,
    color: '#666',
  },
  deleteButton: {
    backgroundColor: '#ff4444',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  deleteButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderWidth: 1,
    borderColor: '#CDDDE2',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    width: '90%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  timeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  timeInputContainer: {
    alignItems: 'center',
  },
  timeInput: {
    borderWidth: 1,
    borderColor: '#CDDDE2',
    borderRadius: 8,
    padding: 8,
    width: 60,
    textAlign: 'center',
    marginHorizontal: 5,
  },
  timeSeparator: {
    fontSize: 24,
    marginHorizontal: 5,
    marginVertical: 15,
  },
  ampmButton: {
    backgroundColor: '#2196F3',
    padding: 8,
    borderRadius: 8,
    marginLeft: 10,
    width: 60,
  },
  ampmButtonText: {
    color: 'white',
    textAlign: 'center',
    fontWeight: '600',
  },
  inputContainer: {
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inputLabel: {
    fontSize: 16,
    flex: 1,
  },
  input: {
    borderWidth: 1,
    borderColor: '#CDDDE2',
    borderRadius: 8,
    padding: 8,
    width: 100,
    textAlign: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  modalButton: {
    flex: 1,
    padding: 15,
    borderRadius: 8,
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: '#ff4444',
  },
  submitButton: {
    backgroundColor: '#2196F3',
  },
  modalButtonText: {
    color: 'white',
    textAlign: 'center',
    fontWeight: '600',
  },
  warningText: {
    color: '#ff4444',
    fontSize: 14,
    lineHeight: 20,
  },
});