import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E6F3FF',
    padding: 16,
  },
  nextScheduleContainer: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#CDDDE2',
  },
  nextScheduleText: {
    fontSize: 16,
    textAlign: 'center',
    color: '#2196F3',
    fontWeight: '600',
  },
  calendar: {
    borderRadius: 10,
    elevation: 4,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#CDDDE2',
  },
  addBar: {
    backgroundColor: '#589cfb',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#CDDDE2',
  },
  addBarText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  schedulesList: {
    flex: 1,
  },
  scheduleItem: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#CDDDE2',
  },
  scheduleInfo: {
    flex: 1,
  },
  scheduleTime: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  scheduleDate: {
    fontSize: 14,
    color: '#666',
  },
  deleteButton: {
    backgroundColor: '#cc3300',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  deleteButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: '#F0F6FF', // Lighter blue background
    borderRadius: 20,
    padding: 25,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
    shadowColor: '#2196F3',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    color: '#2196F3', // Blue color to match theme
  },
  timePickersContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 12,
    paddingVertical: 10,
    shadowColor: '#2196F3',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  wheelPickerWrapper: {
    alignItems: 'center',
    marginHorizontal: 10,
  },
  pickerLabel: {
    fontSize: 16,
    color: '#2196F3',
    marginBottom: 10,
    fontWeight: '600',
  },
  pickerContainer: {
    height: 120,
    width: 60,
    backgroundColor: '#F0F6FF',
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#589CFB',
  },
  scrollPicker: {
    backgroundColor: 'transparent',
  },
  timeSeparator: {
    fontSize: 24,
    marginHorizontal: 5,
    marginTop: 30,
    color: '#2196F3',
    fontWeight: 'bold',
  },
  temperaturePickerContainer: {
    alignItems: 'center',
    marginBottom: 10,
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 12,
    paddingVertical: 15,
    shadowColor: '#2196F3',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  temperatureLabel: {
    fontSize: 16,
    color: '#2196F3',
    marginBottom: 10,
    fontWeight: '600',
  },
  temperaturePickerWrapper: {
    height: 120,
    width: 100,
    backgroundColor: '#F0F6FF',
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#589CFB',
  },
  switchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 20,
    marginBottom: 10,
    backgroundColor: 'white',
    borderRadius: 12,
    paddingVertical: 10,
    shadowColor: '#2196F3',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  switchLabel: {
    fontSize: 16,
    color: '#2196F3',
    fontWeight: '600',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 10,
  },
  modalButton: {
    flex: 1,
    padding: 5,
    borderRadius: 10,
    marginHorizontal: 5,
    alignItems: 'center',
    shadowColor: '#2196F3',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cancelButton: {
    backgroundColor: '#cc3300',
  },
  submitButton: {
    backgroundColor: '#589CFB',
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
});